#!/bin/sh
set -e

platform=$(uname -i)

case $platform in
    i386)
        plat_abi=i386-linux-gnu
        ;;
    x86_64)
        plat_abi=x86_64-linux-gnu
        ;;
    armv7l)
        plat_abi=arm-linux-gnueabihf
        ;;
    *)
        echo "unknown platform for snappy-magic: $platform. remember to file a bug or better yet: fix it :)"
        ;;
esac

exec $SNAP_APP_PATH/bin/$plat_abi/geth --rpc --rpcaddr "0.0.0.0"

# never reach this
exit 1
