#!/bin/sh
set -e

platform=$(uname -i)

case $platform in
    x86_64)
        plat_abi=x86_64-linux-gnu
        ;;
    armv7l)
        plat_abi=arm-linux-gnueabihf
        ;;
    *)
        echo "unknown platform for snappy-magic: $platform. remember to file a bug or better yet: fix it :)"
        ;;
esac
echo "$SNAP_APP_DATA_PATH" | grep -q SNAP_APP && SNAP_APP_DATA_PATH=$HOME
if test -z "$SNAP_APP_DATA_PATH"; then
  SNAP_APP_DATA_PATH=$HOME
fi
mkdir -p $HOME/.ethereum
exec $SNAP_APP_PATH/bin/$plat_abi/geth --rpc --rpcaddr "0.0.0.0"

# never reach this
exit 1
